### ISSUE TITLE
Organize textures into subdirectories

### ISSUE THREAD

**Issue by Calinou** [The-Yak/NobiaxTexturePack#1]
For proper display on GitHub (and the sanity of our file managers), could you reorganize textures to be in subdirectories?

**Comment by The-Yak** [comment]
I prefer the single-folder container for my own personal usage regardless of how it displays on github, so I won't be making this change. Cloning and downloading zip grabs all files even if they don't display on the site.

Feel free to fork though.

**Comment by The-Yak** [comment]
Another user has done this, the reorganized pack can be seen here: https://github.com/gajop/Scenario-Editor-Resources/tree/master/brush_textures/nobiax
